export const APP_NAME = 'KuikChat'
export const APP_TAGLINE = 'The All-in-One Messenger + AI Agent Platform'
export const APP_DESCRIPTION =
  'KuikChat unifies every messaging experience into one sleek, secure, and intelligent app - powered by Hermes AI. No phone number required.'
export const APP_DOMAIN = 'kuikchat.io'
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3100'
export const GITHUB_URL = 'https://github.com/hartm'

export const NAV_ITEMS = [
  { id: 'chats', label: 'Chats', href: '/chats', icon: 'MessageCircle' },
  { id: 'calls', label: 'Calls', href: '/calls', icon: 'Phone' },
  { id: 'status', label: 'Status', href: '/status', icon: 'Circle' },
  { id: 'channels', label: 'Channels', href: '/channels', icon: 'Radio' },
  { id: 'communities', label: 'Communities', href: '/communities', icon: 'Users' },
  { id: 'hermes', label: 'Hermes AI', href: '/hermes', icon: 'Sparkles' },
  { id: 'contacts', label: 'Contacts', href: '/contacts', icon: 'BookUser' },
] as const

export const SETTINGS_NAV = [
  { id: 'profile', label: 'Profile', href: '/settings/profile', icon: 'User' },
  { id: 'privacy', label: 'Privacy', href: '/settings/privacy', icon: 'Eye' },
  { id: 'security', label: 'Security', href: '/settings/security', icon: 'Shield' },
  { id: 'notifications', label: 'Notifications', href: '/settings/notifications', icon: 'Bell' },
  { id: 'appearance', label: 'Appearance', href: '/settings/appearance', icon: 'Palette' },
  { id: 'storage', label: 'Storage & Data', href: '/settings/storage', icon: 'Database' },
  { id: 'billing', label: 'Billing', href: '/settings/billing', icon: 'CreditCard' },
] as const

export const PRICING_TIERS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    priceLabel: '$0',
    period: 'forever',
    description: 'Everything you need to get started.',
    cta: 'Get Started',
    highlight: false,
    features: [
      'Unlimited messages',
      'Voice & video calls (1:1)',
      'Groups up to 256 members',
      'End-to-end encryption',
      'Hermes AI (10 queries/day)',
      '5 GB cloud storage',
      'Status & Stories',
    ],
  },
  {
    id: 'plus',
    name: 'Plus',
    price: 4.99,
    priceLabel: '$4.99',
    period: 'per month',
    description: 'For power users who want more.',
    cta: 'Upgrade to Plus',
    highlight: true,
    features: [
      'Everything in Free',
      'Premium themes & wallpapers',
      'Up to 2 GB file uploads',
      'Extended message history',
      'Custom stickers (AI-generated)',
      '50 GB cloud storage',
      'Hermes AI (200 queries/day)',
      'Ad-free forever',
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 12.99,
    priceLabel: '$12.99',
    period: 'per month',
    description: 'For professionals and creators.',
    cta: 'Go Pro',
    highlight: false,
    features: [
      'Everything in Plus',
      'Professional Mode',
      'Channel monetization (80/20 split)',
      'Advanced analytics',
      'Team inbox (3 seats)',
      'Developer API access',
      '500 GB cloud storage',
      'Hermes AI (unlimited)',
      'Priority support',
    ],
  },
  {
    id: 'business',
    name: 'Business',
    price: 29.99,
    priceLabel: '$29.99',
    period: 'per month',
    description: 'For teams and enterprises.',
    cta: 'Contact Sales',
    highlight: false,
    features: [
      'Everything in Pro',
      'Full CRM integrations',
      'Unlimited team seats',
      'Broadcast lists',
      'Custom branding',
      'Dedicated account manager',
      'SLA & uptime guarantee',
      'On-premise deployment option',
      '99.99% uptime SLA',
    ],
  },
] as const

export const FEATURE_CATEGORIES = [
  {
    id: 'messaging',
    title: 'Messaging Engine',
    icon: 'MessageSquare',
    description: 'Lightning-fast, real-time messaging with everything you expect - and more.',
    features: [
      'Real-time WebSocket delivery',
      'Edit messages (15 min window)',
      'Delete for everyone (no time limit)',
      'Reply, forward, pin, react',
      '@mentions & #hashtags',
      'Bookmarked saved messages',
      'Bold, italic, code formatting',
      'Auto-save drafts per chat',
    ],
  },
  {
    id: 'calls',
    title: 'Voice & Video Calls',
    icon: 'Video',
    description: 'Crystal-clear HD calls with up to 42 participants. Powered by WebRTC.',
    features: [
      '1:1 & group voice calls',
      '1:1 & group video calls (HD 1080p)',
      'Screen sharing',
      'AI noise cancellation',
      'Background blur & virtual backgrounds',
      'Call recording with consent',
      'Picture-in-Picture',
      'Collaborative whiteboard',
      'Live polls during calls',
    ],
  },
  {
    id: 'hermes',
    title: 'Hermes AI Agent',
    icon: 'Sparkles',
    description: 'Your built-in AI assistant. Tag @Hermes anywhere or chat 1:1.',
    features: [
      'In-chat AI (@Hermes)',
      'Real-time translation',
      'Smart replies & summaries',
      'Tone rewriter (pro/casual/friendly)',
      'Image generation (DALL·E)',
      'Custom AI sticker creation',
      'Voice transcription (Whisper)',
      'Document Q&A (PDF, DOCX)',
      'Web search built-in',
      'Meeting notes from calls',
    ],
  },
  {
    id: 'privacy',
    title: 'Privacy & Security',
    icon: 'Shield',
    description: 'Signal-level security meets user-friendly controls. Your data is yours.',
    features: [
      'End-to-end encryption (always on)',
      'Zero-knowledge architecture',
      'Chat Lock (Face ID / fingerprint)',
      'Screen security (block screenshots)',
      'Secret chats (device-only)',
      'Ghost mode (full invisibility)',
      'IP relay protection',
      'Encrypted cloud backups',
      'Self-destruct account option',
    ],
  },
  {
    id: 'groups',
    title: 'Groups & Communities',
    icon: 'Users',
    description: 'Real community infrastructure. Up to 1,024 members per group, unlimited communities.',
    features: [
      'Groups up to 1,024 members',
      'Custom roles & badges',
      'Topic sub-channels',
      'Slow mode & announcement-only',
      'Polls, events, RSVP',
      'Communities (super groups)',
      'Public discovery',
      'Auto-moderation',
    ],
  },
  {
    id: 'channels',
    title: 'Channels & Broadcast',
    icon: 'Radio',
    description: 'Telegram-style channels meets Substack. Build your audience and monetize.',
    features: [
      'Public & private channels',
      'Unlimited subscribers',
      'Paid subscriptions (80% to you)',
      'Scheduled posts',
      'Cross-posting',
      'Rich analytics',
      'Comment threads',
    ],
  },
  {
    id: 'professional',
    title: 'Professional Mode',
    icon: 'Briefcase',
    description: 'LinkedIn meets Slack meets WhatsApp - for business users.',
    features: [
      'Verified business profile',
      'Product catalog',
      'Quick reply templates',
      'Auto-reply & away messages',
      'CRM labels & tagging',
      'Appointment booking',
      'Invoice sharing',
      'Team inbox',
      'CRM integrations',
    ],
  },
  {
    id: 'expression',
    title: 'Fun & Expression',
    icon: 'Smile',
    description: 'Stickers, themes, GIFs, AR filters - be yourself in every chat.',
    features: [
      'AI-generated custom stickers',
      'GIPHY & Tenor integration',
      'Light / Dark / AMOLED themes',
      'Per-chat wallpapers',
      'AR camera filters',
      'Cartoon emoji avatars',
      'Animated Lottie stickers',
    ],
  },
] as const

export const HERMES_MODES = [
  { id: 'professional', label: '🧑‍💼 Professional', description: 'Formal, concise, business-focused' },
  { id: 'casual', label: '😄 Casual', description: 'Friendly, conversational, relaxed' },
  { id: 'creative', label: '🎨 Creative', description: 'Expressive, imaginative, artistic' },
  { id: 'analytical', label: '🔬 Analytical', description: 'Data-driven, precise, detailed' },
  { id: 'multilingual', label: '🌐 Multilingual', description: 'Auto-detect and respond in your language' },
] as const

export const DISAPPEARING_OPTIONS = [
  { value: 0, label: 'Off' },
  { value: 30, label: '30 seconds' },
  { value: 300, label: '5 minutes' },
  { value: 3600, label: '1 hour' },
  { value: 86400, label: '24 hours' },
  { value: 604800, label: '7 days' },
  { value: 2419200, label: '4 weeks' },
] as const
