FROM node:20-alpine AS deps
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

FROM node:20-alpine AS builder
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_APP_DOMAIN
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG NEXT_PUBLIC_ANDROID_DOWNLOAD_ENABLED
ARG NEXT_PUBLIC_IOS_STATUS
ARG NEXT_PUBLIC_ENABLE_CALLS
ARG NEXT_PUBLIC_ENABLE_HERMES
ARG NEXT_PUBLIC_ENABLE_STRIPE

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_APP_DOMAIN=$NEXT_PUBLIC_APP_DOMAIN
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NEXT_PUBLIC_ANDROID_DOWNLOAD_ENABLED=$NEXT_PUBLIC_ANDROID_DOWNLOAD_ENABLED
ENV NEXT_PUBLIC_IOS_STATUS=$NEXT_PUBLIC_IOS_STATUS
ENV NEXT_PUBLIC_ENABLE_CALLS=$NEXT_PUBLIC_ENABLE_CALLS
ENV NEXT_PUBLIC_ENABLE_HERMES=$NEXT_PUBLIC_ENABLE_HERMES
ENV NEXT_PUBLIC_ENABLE_STRIPE=$NEXT_PUBLIC_ENABLE_STRIPE

COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN npm run build

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
COPY --from=builder /app/next.config.js ./next.config.js

EXPOSE 3100
CMD ["npm", "run", "start"]
